title: Quartierverein Oberdorf Zufikon
description: Familien und Einzelpersonen die geselliges Beisammensein schätzen, Freundschaften pflegen.

url: http://www.qv-zufikon.ch
baseurl: ""
# paginate_path: "blog/page:num/"
# permalink: blog/:title/

markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-paginate
  - jekyll-google-photos
paginate: 5

toc:
  - title: Verein
    subfolderitems:
      - page: Verein
        url: /start
      - page: Kontakt
        url: /kontakt
      - page: Statuten
        url: /statuten
  - title: Programm
    subfolderitems:
      - page: 2019
        url: /programm-2
      - page: 2018
        url: /programm-2018
      - page: 2017
        url: /programm
  - title: Berichte
    url: /index.html
  - title: Gallery
    url: /gallery

social:
   email: info@qv-zufikon.ch

google_analytics: "UA-151259011-1"
